[package]
name = "estrange-cli"
version = "0.1.1"
edition = "2021"
repository = "https://github.com/kalley/estrange"

[dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.0", features = ["derive"] }
dirs = "5.0"
prometheus = "0.14.0"
prometheus-reqwest-remote-write = "0.4.0"
reqwest = { version = "0.12", features = ["json"] }
rusqlite = "0.29"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.0"
tokio = { version = "1.0", features = ["full"] }
toml = "0.8"
